{
 "title": "Pipeline API Observability",
 "description": "Telemetry FastAPI application with three pillars of observability: Traces (Tempo), Metrics (Prometheus), Logs (Loki) on Grafana through OpenTelemetry and OpenMetrics.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_app_info{}, app_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "starlette_requests_in_progress{path!=\"/metrics\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlette_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlette_request_duration_seconds_sum / starlette_request_duration_seconds_count",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(starlette_request_duration_seconds_bucket{path!=\"/metrics\"}[1m])) by(path, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(starlette_requests_total[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "candlestick",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlette_request_duration_seconds_count",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Python GC Objects  Collected Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}