apiVersion: v1
entries:
  grafana:
  - apiVersion: v2
    appVersion: 9.3.6
    created: "2023-03-03T16:20:44.855868-05:00"
    description: The leading tool for querying and visualizing time series and metrics.
    digest: b7a515dcfc739b1b995a5216c07535d437652b4865a797f21d4ad1958c8b3952
    home: https://grafana.net
    icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: mail@torstenwalter.de
      name: torstenwalter
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    type: application
    urls:
    - https://unstructured-io.github.io/prometheus-community-helm-charts/charts/kube-prometheus-stack/charts/grafana-6.50.8.tgz
    version: 6.50.8
  kube-prometheus-stack:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus-operator/kube-prometheus
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: v0.63.0
    created: "2023-03-03T16:20:44.854163-05:00"
    dependencies:
    - condition: kubeStateMetrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.31.*
    - condition: nodeExporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.14.*
    - condition: grafana.enabled
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 6.50.*
    description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards,
      and Prometheus rules combined with documentation and scripts to provide easy
      to operate end-to-end Kubernetes cluster monitoring with Prometheus using the
      Prometheus Operator.
    digest: f021e24c2dc412bfd72c4e6b30a7000f7288809ed17447104b5b2c9b5ba55603
    home: https://github.com/prometheus-operator/kube-prometheus
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - operator
    - prometheus
    - kube-prometheus
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: andrew@quadcorps.co.uk
      name: andrewgkew
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: github.gkarthiks@gmail.com
      name: gkarthiks
    - email: kube-prometheus-stack@sisti.pt
      name: GMartinez-Sisti
    - email: scott@r6by.com
      name: scottrigby
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: quentin.bisson@gmail.com
      name: QuentinBisson
    name: kube-prometheus-stack
    sources:
    - https://github.com/prometheus-community/helm-charts
    - https://github.com/prometheus-operator/kube-prometheus
    type: application
    urls:
    - https://unstructured-io.github.io/prometheus-community-helm-charts/charts/kube-prometheus-stack/kube-prometheus-stack-45.4.0.tgz
    version: 45.4.0
  kube-state-metrics:
  - apiVersion: v2
    appVersion: 2.8.0
    created: "2023-03-03T16:20:44.856531-05:00"
    description: Install kube-state-metrics to generate and expose cluster-level metrics
    digest: f069650d767d4cf68664418274cf97892e0b99ed79ed37f6b449d9c94ec0266d
    home: https://github.com/kubernetes/kube-state-metrics/
    keywords:
    - metric
    - monitoring
    - prometheus
    - kubernetes
    maintainers:
    - email: tariq.ibrahim@mulesoft.com
      name: tariq1890
    - email: manuel@rueg.eu
      name: mrueg
    - email: david@0xdc.me
      name: dotdc
    name: kube-state-metrics
    sources:
    - https://github.com/kubernetes/kube-state-metrics/
    type: application
    urls:
    - https://unstructured-io.github.io/prometheus-community-helm-charts/charts/kube-prometheus-stack/charts/kube-state-metrics-4.31.0.tgz
    version: 4.31.0
  prometheus-node-exporter:
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2023-03-03T16:20:44.857258-05:00"
    description: A Helm chart for prometheus node-exporter
    digest: 28aab7db20f3e5caae6f7217d3d1bf17fbc940ca3e58de97ccfecc41d8d75e9d
    home: https://github.com/prometheus/node_exporter/
    keywords:
    - node-exporter
    - prometheus
    - exporter
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    name: prometheus-node-exporter
    sources:
    - https://github.com/prometheus/node_exporter/
    type: application
    urls:
    - https://unstructured-io.github.io/prometheus-community-helm-charts/charts/kube-prometheus-stack/charts/prometheus-node-exporter-4.14.0.tgz
    version: 4.14.0
generated: "2023-03-03T16:20:44.836956-05:00"
